# Render Blueprint Configuration
# This file defines how to deploy The Amplitude Institute website on Render

services:
  - type: web
    name: amplitude-institute
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    
    # Environment configuration
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: jmcconocha@abydosone.ltd
      - key: ADMIN_PASSWORD
        value: TempAdmin123!
      - key: SITE_URL
        value: https://amplitude-institute.onrender.com
      - key: USE_POSTGRESQL
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: amplitude-db
          property: connectionString
    
    # Scaling (free tier limitations)
    numInstances: 1
    
    # Auto-deploy settings  
    autoDeploy: true

databases:
  - name: amplitude-db
    plan: free
    databaseName: amplitude_institute
    user: amplitude_user

# Static site alternative (if Docker doesn't work on free tier)
# Uncomment and modify if needed:
#
# - type: static_site
#   name: amplitude-institute-static
#   buildCommand: echo "No build needed"
#   publishPath: .
#   pullRequestPreviewsEnabled: true
#   
#   # Static file routing
#   routes:
#     - type: rewrite
#       source: /*
#       destination: /index.html
#   
#   # Environment variables for static site
#   envVars:
#     - key: NODE_ENV
#       value: production
#   
#   # Headers for static assets
#   headers:
#     - path: /*
#       name: X-Frame-Options
#       value: DENY
#     - path: /*
#       name: X-Content-Type-Options
#       value: nosniff
#     - path: /
#       name: Cache-Control
#       value: no-cache
#     - path: /static/*
#       name: Cache-Control
#       value: public, max-age=31536000, immutable